create table if not exists public.saved_products (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  brand text not null default '',
  name text not null,
  product_type text not null default '상의',
  size text not null default '표기 없음',
  condition text not null default 'B+ 좋은 상태',
  price integer not null default 0,
  description text not null default '',
  measurements jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.saved_products enable row level security;

drop policy if exists "saved_products_select_own" on public.saved_products;
create policy "saved_products_select_own"
on public.saved_products for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "saved_products_insert_own" on public.saved_products;
create policy "saved_products_insert_own"
on public.saved_products for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "saved_products_update_own" on public.saved_products;
create policy "saved_products_update_own"
on public.saved_products for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "saved_products_delete_own" on public.saved_products;
create policy "saved_products_delete_own"
on public.saved_products for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists public.inventory_products (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  product_key text not null,
  code text not null default '',
  barcode text not null default '',
  name text not null,
  brand text not null default '',
  size text not null default '',
  product_type text not null default '상의',
  price integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, product_key)
);

alter table public.inventory_products enable row level security;

drop policy if exists "inventory_products_select_own" on public.inventory_products;
create policy "inventory_products_select_own"
on public.inventory_products for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "inventory_products_insert_own" on public.inventory_products;
create policy "inventory_products_insert_own"
on public.inventory_products for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "inventory_products_update_own" on public.inventory_products;
create policy "inventory_products_update_own"
on public.inventory_products for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "inventory_products_delete_own" on public.inventory_products;
create policy "inventory_products_delete_own"
on public.inventory_products for delete
to authenticated
using (auth.uid() = user_id);

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.saved_products to authenticated;
grant select, insert, update, delete on public.inventory_products to authenticated;
grant usage, select on all sequences in schema public to authenticated;
